import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('english'); // Default is now english as requested

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'hindi' ? 'english' : 'hindi'));
  };

  const t = {
    hindi: {
      appName: 'न्यायAI',
      home: 'मुख्य',
      analyze: 'विश्लेषण',
      ask: 'चैट',
      draft: 'ड्राफ्ट',
      toggle: 'English',
      // Landing Page
      nextGenAI: 'नया युग कानूनी AI',
      heroTitle: 'Universal Justice',
      heroSubtitle: 'Augmented by AI',
      heroDescription: 'कानूनी बुद्धिमत्ता के भविष्य का अनुभव करें। NyayAI दस्तावेज़ विश्लेषण, स्मार्ट ड्राफ्टिंग और कानूनी परामर्श प्रदान करता है—पूरी तरह से निजी और तेज़।',
      initializeWorkspace: 'कार्यक्षेत्र शुरू करें',
      exploreTechnology: 'तकनीकी अन्वेषण',
      carouselTitle: 'Neural Legal Core अन्वेषण',
      accuracyRate: 'सटीकता दर',
      analysisSpeed: 'विश्लेषण गति',
      privateOffline: 'निजी और ऑफलाइन',
      capabilitiesTitle: 'Powerful Capabilities',
      analyzeTitle: 'दस्तावेज़ विश्लेषण',
      askTitle: 'Neural Hub चैट',
      draftTitle: 'Smart Composer',
      analyzeDesc: 'छिपे हुए क्लॉज, जोखिमों को पहचानें और जटिल कानूनी दस्तावेजों का तुरंत सारांश प्राप्त करें।',
      askDesc: 'हमारे कानूनी दिमाग के साथ संवाद करें। जटिल सवाल पूछें और सटीक उत्तर प्राप्त करें।',
      draftDesc: 'सरल संकेतों से सेकंडों में पेशेवर, कानूनी रूप से सही ड्राफ्ट तैयार करें।',
      ctaTitle: 'Ready to transform your practice?',
      ctaDescription: 'कानून के क्षेत्र में नई संभावनाओं को परिभाषित करने के लिए NyayAI का उपयोग करने वाले विशिष्ट कानूनी पेशेवरों में शामिल हों।',
      getStartedFree: 'मुफ्त में शुरू करें',
      // Auth Pages
      loginTitle: 'Welcome Back',
      loginSubtitle: 'अपने सुरक्षित न्यूरल कार्यक्षेत्र में लॉग इन करें',
      registerTitle: 'Create Account',
      registerSubtitle: 'NyayAI के साथ कानूनी तकनीक के भविष्य में शामिल हों',
      emailLabel: 'ईमेल पता',
      passwordLabel: 'पासवर्ड',
      fullNameLabel: 'पूरा नाम',
      signIn: 'साइन इन करें',
      register: 'रजिस्टर करें',
      signingIn: 'साइन इन हो रहा है...',
      registering: 'रजिस्टर हो रहा है...',
      noAccount: 'खाता नहीं है?',
      haveAccount: 'पहले से खाता है?',
      registerLink: 'यहाँ रजिस्टर करें',
      signInLink: 'साइन इन करें',
      logout: 'लॉगआउट',
      // Footer
      footerDesc: 'अत्याधुनिक आर्टिफिशियल इंटेलिजेंस के माध्यम से सार्वभौमिक न्याय। निजी, सुरक्षित और सुलभ कानूनी तकनीक।',
      platformStatus: 'प्लेटफॉर्म स्थिति: स्वस्थ',
      techCol: 'तकनीकी',
      orgCol: 'संगठन',
      legalCol: 'कानूनी',
      missionLink: 'हमारा मिशन',
      contactLink: 'संपर्क करें',
      partnerPortal: 'पार्टनर पोर्टल',
      securityWhitepaper: 'सुरक्षा श्वेतपत्र',
      privacyEthics: 'गोपनीयता नैतिकता',
      designedWith: 'बुद्धिमत्ता के साथ डिजाइन किया गया',
      // Pages
      aboutTitle: 'About NyayAI',
      missionTitle: 'हमारा मिशन',
      contactTitle: 'हमसे संपर्क करें',
      contactSubtitle: 'हम यहाँ मदद के लिए हैं। NyayAI टीम से संपर्क करें।',
      loginRequired: 'प्रवेश करने से पहले लॉगिन करना आवश्यक है।',
      forgotPasswordTitle: 'पासवर्ड भूल गए?',
      forgotPasswordLink: 'पासवर्ड भूल गए?',
      forgotPasswordSubtitle: 'चिंता न करें, अपना ईमेल दर्ज करें और हम आपको पासवर्ड रीसेट करने का लिंक भेजेंगे।',
      resetPasswordBtn: 'रीसेट लिंक भेजें',
      backToLogin: 'लॉगिन पर वापस जाएं',
      resetEmailSent: 'रीसेट लिंक आपके ईमेल पर भेज दिया गया है!',
      // Chat
      aiRole: 'Neural Counsel',
      userRole: 'Legal Inquirer',
      welcomeTextChat: 'आपका विशिष्ट AI कानूनी परामर्शदाता तैयार है। तत्काल मार्गदर्शन के लिए कोई भी प्रश्न पूछें।',
      // Analyzer
      dropFileText: 'न्यूरल विश्लेषण के लिए अपने कानूनी दस्तावेज यहाँ छोड़ें',
      deepAnalyzeBtn: 'गहन विश्लेषण करें',
      intelNoteTitle: 'Intelligence Note',
      intelNoteDesc: 'NyayAI-v2 कोर का उपयोग करके विश्लेषण किया गया। सभी प्रोसेसिंग आपके स्थानीय सुरक्षित वातावरण में पूरी हुई।',
      // Drafting
      docExcerptLabel: 'कानूनी दस्तावेज़ का अंश',
      situationLabel: 'आपकी स्थिति',
      draftSubtitle: 'सटीकता के साथ कानूनी रूप से सही प्रतिक्रियाएं और दस्तावेज तैयार करने के लिए न्यूरल बुद्धिमत्ता का उपयोग करें।',
      draftResultTitle: 'न्यूरल ड्राफ्ट तैयार',
      copyBtn: 'क्लिपबोर्ड पर कॉपी करें',
      // Analyzer Dashboard
      confidence: 'आत्मविश्वास',
      brainSummary: 'ब्रेन सारांश',
      nextSteps: 'अगला कदम (Next Steps)',
      detectedStatutes: 'संसूचित कानून',
      docType: 'दस्तावेज़ प्रकार',
      readyForProcessing: 'प्रसंस्करण के लिए तैयार',
      startAnalysis: 'न्यूरल विश्लेषण शुरू करें',
      browseFiles: 'या स्थानीय फ़ाइलें ब्राउज़ करने के लिए क्लिक करें (PDF, PNG, JPG, WEBP)',
      analyzerHeroDesc: 'तत्काल न्यूरल प्रोसेसिंग और जोखिम पहचान के लिए कोई भी कानूनी दस्तावेज़ या उसकी छवि अपलोड करें।',
      // Workspace
      workspace: 'कार्यक्षेत्र',
      workspaceTitle: 'एकीकृत कार्यक्षेत्र',
      workspaceSubtitle: 'अपने कानूनी दस्तावेज़ को अपलोड करें और न्यूरल विश्लेषण, प्रासंगिक प्रश्नोत्तर, और स्वचालित ड्राफ्टिंग को एक ही स्थान पर अनलॉक करें।',
      workspaceChatSubtitle: 'उपरोक्त दस्तावेज़ के संबंध में कोई भी विशिष्ट प्रश्न पूछें। AI के पास यह संदर्भ में है।',
      workspaceDraftSubtitle: 'अपलोड किए गए दस्तावेज़ के आधार पर तुरंत एक औपचारिक उत्तर का मसौदा तैयार करने के लिए अपनी स्थिति का वर्णन करें।',
      // Common
      upload: 'अपलोड करें',
      selectFile: 'फ़ाइल चुनें',
      send: 'भेजें',
      generate: 'तैयार करें',
      explanation: 'व्याख्या',
      references: 'कानूनी संदर्भ',
      placeholderAsk: 'अपना सवाल यहाँ लिखें...',
      placeholderSituation: 'अपनी स्थिति का वर्णन करें...',
    },
    english: {
      appName: 'NyayAI',
      home: 'Home',
      analyze: 'Analyze',
      ask: 'Chat',
      draft: 'Draft',
      toggle: 'हिंदी',
      // Landing Page
      nextGenAI: 'NEXT-GEN LEGAL AI',
      heroTitle: 'Universal Justice',
      heroSubtitle: 'Augmented by AI',
      heroDescription: 'Experience the future of legal intelligence. NyayAI provides elite document analysis, intelligent drafting, and legal consultation—all offline, private, and lightning fast.',
      initializeWorkspace: 'Initialize Workspace',
      exploreTechnology: 'Explore Technology',
      carouselTitle: 'Explore Neural Legal Core',
      accuracyRate: 'Accuracy Rate',
      analysisSpeed: 'Analysis Speed',
      privateOffline: 'Private & Offline',
      capabilitiesTitle: 'Powerful Capabilities',
      analyzeTitle: 'Precision Analysis',
      askTitle: 'Neural Hub',
      draftTitle: 'Smart Composer',
      analyzeDesc: 'Extract hidden clauses, identify risks, and summarize complex legal documents with neural-grade accuracy.',
      askDesc: 'Interact with our high-performance legal brain. Ask complex questions and receive immediate, expert-level counsel.',
      draftDesc: 'Generate professional, legally-sound responses and drafts from simple natural language prompts in seconds.',
      ctaTitle: 'Ready to transform your practice?',
      ctaDescription: 'Join the elite legal professionals using NyayAI to redefine what\'s possible in law.',
      getStartedFree: 'Get Started for Free',
      // Auth Pages
      loginTitle: 'Welcome Back',
      loginSubtitle: 'Log in to your secure neural workspace',
      registerTitle: 'Create Account',
      registerSubtitle: 'Join the future of legal tech with NyayAI.',
      emailLabel: 'Email Address',
      passwordLabel: 'Password',
      fullNameLabel: 'Full Name',
      signIn: 'Sign In',
      register: 'Register',
      signingIn: 'Signing In...',
      registering: 'Registering...',
      noAccount: 'Don\'t have an account?',
      haveAccount: 'Already have an account?',
      registerLink: 'Register here',
      signInLink: 'Sign in instead',
      logout: 'Logout',
      // Footer
      footerDesc: 'Universal justice through elite artificial intelligence. Private, secure, and accessible legal technology.',
      platformStatus: 'Platform Status: Healthy',
      techCol: 'Technology',
      orgCol: 'Organization',
      legalCol: 'Legal',
      missionLink: 'Our Mission',
      contactLink: 'Get in Touch',
      partnerPortal: 'Partner Portal',
      securityWhitepaper: 'Security Whitepaper',
      privacyEthics: 'Privacy Ethics',
      designedWith: 'Designed with Intelligence',
      // Pages
      aboutTitle: 'About NyayAI',
      missionTitle: 'Our Mission',
      contactTitle: 'Contact Us',
      contactSubtitle: 'We\'re here to help. Reach out to the NyayAI team.',
      loginRequired: 'Login should be done before getting in.',
      forgotPasswordTitle: 'Forgot Password?',
      forgotPasswordLink: 'Forgot Password?',
      forgotPasswordSubtitle: 'Don\'t worry, enter your email and we\'ll send you a reset link.',
      resetPasswordBtn: 'Send Reset Link',
      backToLogin: 'Back to Login',
      resetEmailSent: 'Reset link has been sent to your email!',
      // Chat
      aiRole: 'Neural Counsel',
      userRole: 'Legal Inquirer',
      welcomeTextChat: 'Your elite AI legal counsel is ready. Ask any question for instant professional guidance.',
      // Analyzer
      dropFileText: 'Drop your legal documents here for neural analysis',
      deepAnalyzeBtn: 'Deep Analyze',
      intelNoteTitle: 'Intelligence Note',
      intelNoteDesc: 'Analysis performed using NyayAI-v2 core. All processing completed offline on your local secure environment.',
      // Drafting
      docExcerptLabel: 'Legal Document Excerpt',
      situationLabel: 'Your Situation',
      draftSubtitle: 'Harness neural intelligence to draft legally sound responses and documents with precision.',
      draftResultTitle: 'Neural Response Drafted',
      copyBtn: 'Copy to Clipboard',
      // Analyzer Dashboard
      confidence: 'Confidence',
      brainSummary: 'Brain Summary',
      nextSteps: 'Next Steps',
      detectedStatutes: 'Detected Statutes',
      docType: 'Document Type',
      readyForProcessing: 'READY FOR PROCESSING',
      startAnalysis: 'Start Neural Analysis',
      browseFiles: 'or click to browse local files (PDF, PNG, JPG, WEBP)',
      analyzerHeroDesc: 'Upload any legal document or image for instant neural processing and risk identification.',
      // Workspace
      workspace: 'Workspace',
      workspaceTitle: 'Unified Workspace',
      workspaceSubtitle: 'Upload your legal document to instantly unlock Neural Analysis, Contextual Q&A, and Automated Drafting in one place.',
      workspaceChatSubtitle: 'Ask any specific questions regarding the document above. The AI has it in context.',
      workspaceDraftSubtitle: 'Describe your situation to instantly draft a formal reply based on the uploaded document.',
      // Common
      upload: 'Upload',
      selectFile: 'Select File',
      send: 'Send',
      generate: 'Generate',
      explanation: 'Explanation',
      references: 'Legal References',
      placeholderAsk: 'Type your question here...',
      placeholderSituation: 'Describe your situation...',
    }
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, translations: t[language], t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
